export class ExamError extends Error {
  constructor(
    public readonly code:
      | "validation_failed"
      | "exam_not_found"
      | "exam_not_draft"
      | "exam_has_attempts"
      | "exam_not_publishable"
      | "course_mismatch"
      | "passage_not_found"
      | "asset_not_found"
      | "asset_not_image"
      | "alt_text_required"
      | "audio_policy_invalid"
      | "must_include_all_passages"
      | "unknown_passage"
      | "attempt_not_found"
      | "attempt_already_submitted"
      | "attempt_belongs_to_other"
      | "session_stale"
      | "not_enrolled"
      | "exam_not_open"
      | "exam_window_closed"
      | "question_not_in_exam"
      | "answer_not_found"
      | "score_out_of_range"
      | "not_manual_gradable"
      | "duration_extension_too_large"
      | "reason_required"
      | "attempt_not_in_progress"
      | "attempt_not_submitted"
      | "message_body_required"
      | "message_too_long"
      | "message_not_found"
      | "invalid_code"
      | "access_mode_mismatch"
      | "open_max_attempts_reached"
      | "candidate_disabled"
      | "candidate_email_required"
      | "candidate_phone_required"
      | "candidate_name_required"
      | "result_not_found"
      | "result_not_yet_graded"
      | "candidate_not_found"
      | "candidate_has_attempts"
      | "candidate_code_collision"
      | "bank_not_found"
      | "bank_has_used_questions"
      | "bank_question_not_found"
      | "bank_question_in_use"
      | "bank_question_not_publishable"
      | "bank_question_already_archived"
      | "cohort_not_found"
      | "cohort_required"
      | "cohort_name_taken"
      | "schedule_not_found"
      | "schedule_invalid_window"
      | "section_not_found"
      | "section_pool_empty"
      | "section_pool_underfilled"
      | "round_not_found"
      | "round_code_taken"
      | "round_invalid_window"
      | "round_requires_at_least_one_course"
      | "round_admin_already_exists"
      | "round_course_already_added"
      | "forbidden"
      // A6.1 — Vấn đáp AI
      | "exam_not_oral"
      | "exam_not_written"
      | "material_not_found"
      | "unsupported_material_type",
    public readonly details?: unknown,
  ) {
    super(code);
  }
}
